name: floto
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3513827321585268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.24579810514114797
  saturation: 0.7932094924617559
  rhythmicContrast: 0.5823826771229506
purpose: []
